# Generated by Django 2.1.3 on 2018-11-10 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('imid', models.AutoField(primary_key=True, serialize=False)),
                ('imagePath', models.CharField(max_length=4096)),
                ('thumbnailPath', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('DE', 'Denied'), ('SO', 'Sold')], default='PE', max_length=2)),
                ('createdAd', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('approvedAt', models.DateTimeField(auto_now_add=True)),
                ('isBook', models.BooleanField()),
                ('courseNumber', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Items'),
        ),
    ]
