# Generated by Django 2.1.3 on 2018-11-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='createdAd',
            new_name='createdAt',
        ),
        migrations.AlterField(
            model_name='items',
            name='modifiedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
