# Generated by Django 2.1.3 on 2018-11-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locations',
            fields=[
                ('lid', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('map', models.CharField(max_length=4096)),
            ],
        ),
    ]
